#!/usr/bin/env node
// Generate the Cloudflare Pages / Netlify `_headers` file for the build
// output from the SAME environment Vite built with (audit L-14).
//
//   npm run build   →   vite build && node scripts/gen-headers.mjs
//
// The Content-Security-Policy's connect-src / img-src list exactly one
// remote origin: the indexer named by VITE_INDEXER_URL. Nothing else is
// ever fetched or loaded (fonts are self-hosted; mempool.space is a link
// target only and needs no CSP entry). A production build therefore
// carries no loopback origins; a loopback VITE_INDEXER_URL (a local
// build pointed at a local indexer) is listed as such. style-src is
// 'self' without 'unsafe-inline': React writes the few dynamic styles
// through the CSSOM (element.style), which CSP does not restrict, and
// there are no <style> elements or style="" attributes in the markup.
//
// Env resolution mirrors Vite (.env, .env.<mode>, .env.local,
// .env.<mode>.local; process.env wins). Mode: --mode <m>, else MODE, else
// "production". Output: --out <path> (default dist/_headers).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_INDEXER_URL = "http://127.0.0.1:8765";

/** https with a hostname, or http to a loopback host — same rule as src/lib/indexer.js. */
export function isAllowedIndexerUrl(url) {
  let u;
  try {
    u = new URL(url);
  } catch {
    return false;
  }
  if (u.hostname.length === 0) return false;
  if (u.protocol === "https:") return true;
  const loopback = u.hostname === "localhost" || u.hostname === "127.0.0.1" || u.hostname === "[::1]";
  return u.protocol === "http:" && loopback;
}

/** Minimal .env parser (KEY=value, optional quotes, # comments). */
export function parseDotenv(text) {
  const out = {};
  for (const line of String(text || "").split(/\r?\n/)) {
    const m = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/.exec(line);
    if (!m) continue;
    let v = m[2];
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    else v = v.replace(/\s+#.*$/, "");
    out[m[1]] = v;
  }
  return out;
}

/** Vite's precedence: .env < .env.<mode> < .env.local < .env.<mode>.local < process.env. */
export function loadEnv(mode, dir, processEnv = process.env) {
  const files = [".env", `.env.${mode}`, ".env.local", `.env.${mode}.local`];
  let env = {};
  for (const f of files) {
    const p = join(dir, f);
    if (existsSync(p)) env = { ...env, ...parseDotenv(readFileSync(p, "utf8")) };
  }
  for (const [k, v] of Object.entries(processEnv)) if (k.startsWith("VITE_")) env[k] = v;
  return env;
}

/**
 * The `_headers` text for a build. Pure: { indexerUrl, mode } → string.
 * `indexerUrl` is validated exactly like the app validates it; an
 * invalid or missing value falls back to the app's default (loopback) —
 * which in production mode is an error, because such a bundle talks to
 * nothing.
 */
export function buildHeaders({ indexerUrl, mode = "production", strict = false, warn = () => {} } = {}) {
  const configured = String(indexerUrl || "").trim();
  const url = configured && isAllowedIndexerUrl(configured) ? configured : DEFAULT_INDEXER_URL;
  const origin = new URL(url).origin;
  const loopback = origin.startsWith("http:");
  if (mode === "production" && loopback) {
    const msg = `gen-headers: VITE_INDEXER_URL="${configured || "(unset)"}" is not an https origin — a production build must name the real indexer`;
    // On a deploy platform (Cloudflare Pages sets CF_PAGES, most CI sets CI)
    // this is fatal; a local `npm run build` gets a loud warning and a
    // loopback-only CSP, which is harmless because such a bundle only ever
    // runs against a local indexer.
    if (strict) throw new Error(msg);
    warn(`${msg} (writing a loopback-only CSP for this local build)`);
  }
  const csp = [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self'",
    `img-src 'self' data: blob: ${origin}`,
    "font-src 'self' data:",
    `connect-src 'self' ${origin}`,
    "worker-src 'self' blob:",
    "manifest-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    "form-action 'none'",
  ].join("; ");
  return [
    "# GENERATED by scripts/gen-headers.mjs at build time — do not edit; change the script.",
    `# mode=${mode} indexer=${origin}`,
    "#",
    "# LuckyProtocol web holds NO keys (signing is delegated to the wallet),",
    "# but a strict CSP still matters: an XSS could swap the PSBT the user is",
    "# asked to sign, or repoint indexer reads at a poisoned origin. The bundle",
    "# is fully self-contained (fonts via @fontsource, no CDNs, no inline",
    "# scripts or styles), so script-src and style-src are 'self' only and the",
    "# only remote origin is the indexer (connect-src for reads, img-src for",
    "# token avatars served by it).",
    "",
    "/*",
    `  Content-Security-Policy: ${csp}`,
    "  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload",
    "  X-Content-Type-Options: nosniff",
    "  X-Frame-Options: DENY",
    "  Referrer-Policy: strict-origin-when-cross-origin",
    "  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), bluetooth=()",
    "  Cross-Origin-Opener-Policy: same-origin",
    "  Cross-Origin-Resource-Policy: same-origin",
    "",
    "# Hashed JS/CSS chunks in /assets/ are content-addressed (Vite appends a",
    "# hash to the filename), so they can be cached forever.",
    "/assets/*",
    "  Cache-Control: public, max-age=31536000, immutable",
    "",
  ].join("\n");
}

function main(argv) {
  const args = argv.slice(2);
  const opt = (name) => {
    const i = args.indexOf(name);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const mode = opt("--mode") || process.env.MODE || "production";
  const out = resolve(root, opt("--out") || "dist/_headers");
  const env = loadEnv(mode, root);
  const strict = !!(process.env.CF_PAGES || process.env.CI);
  const text = buildHeaders({ indexerUrl: env.VITE_INDEXER_URL, mode, strict, warn: (m) => console.warn(m) });
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, text, "utf8");
  console.log(`gen-headers: wrote ${out} (mode=${mode}, indexer=${new URL(env.VITE_INDEXER_URL && isAllowedIndexerUrl(env.VITE_INDEXER_URL) ? env.VITE_INDEXER_URL : DEFAULT_INDEXER_URL).origin})`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv);
}
